# -*- coding: utf-8 -*-
"""atm_machine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfmO7WqFzbZC0sezVtFKrOGlMEsGc1Af
"""

print("Welcome to NeoCloud Automated Teller Machine")

# We created a variable here that stores all the data of the users
# The variable is what we call a nested dictionary in python

data = {"Peace":{"password":1234 , "balance":1000}}


def logIn():
  '''
  This function authenticates and logins in user
  '''
  user_name = input("Input your name: ")
  if user_name in data:
    print("Account exist ")
    user_password = input("Enter your Password: ")

    if int(data[user_name]["password"]) == int(user_password):
      print("Verified")
      return user_name

    else:
      retryPassword(user_name)
      return user_name


  else:
    new_user_age = input("Enter a Password To Create Account: ")
    data[user_name] = {}
    data[user_name]["password"] = int(new_user_age)
    data[user_name]["balance"] = 0
    print("Account created")
    logIn()

    return user_name





def retryPassword(user_name):
  '''
  This function retries the password if incorrect

  '''
  attempts = 0
  while(attempts < 3):
    attempts += 1
    if attempts == 3:
      print("Too many attempts")
    else:
      print("Incorrect password, Try again")
      user_password = input("Enter your Password: ")
      if int(data[user_name]["password"]) == int(user_password):
        print("Verified")
        break





def deposit():
  '''
  This function deposits money into the account

  '''
  user_name = logIn()
  amount = input("Input amount to deposit: ")

  data[user_name]["balance"] =  int(data[user_name]["balance"]) +  int(amount)
  print(f'Deposit successful , your new balance is {data[user_name]["balance"]}')



def withdraw():
  '''
  This function withdraws money from the account

  '''
  user_name = logIn()
  amount = input("Input amount to withdraw: ")
  if int(data[user_name]["balance"]) < int(amount):
    print("Insufficient balance")
  else:
    data[user_name]["balance"] =  int(data[user_name]["balance"]) -  int(amount)
    print(f'Withdrawal successful , your new balance is {data[user_name]["balance"]}')


def viewBalance():
  '''
  This function views the balance of the account

  '''
  user_name = logIn()
  print(f'Your balance is {data[user_name]["balance"]}')

# This print just output what actions a user can perform in the atm

print(
    "  \n1: To create Account \n2: To deposit \n3: To Withdraw \n4: To view balance \n5: To end "
  )
endProcess = False
while(endProcess == False):
  # we request the user to select an action with this line of code
  action = input( "\nSelect an action with the action Number: " )

  # we use the conditonal statement to check if the action is valid and call the right function based on the action selected

  if (int(action) == 1):
    # we create a new account or log in if 1 is selected
    print("create Account or logIn")
    logIn()

  elif (int(action) == 2):
    # we deposit money into out account by calling the deposit function  if action  2  is selected
    deposit()

  elif (int(action) == 3):
    # we withdraw money from account here by calling the withdraw function if 3 is selected
    withdraw()

  elif (int(action) == 4):
    # This is just to view our current balance by selection 4 as action
    viewBalance()

  else:
    if (int(action) == 5):
      #This ends the process by selecting 5
      endProcess = True
      print("Thank you for using Neocloud ATM")
    else:
      print("Invalid action")
      break

